In [79]:
import pandas as pd
from faker import Faker
import numpy as np

In [2]:
faker=Faker('zh-CN')

In [10]:
data=pd.Series(range(1,5))
print(type(data))
data

<class 'pandas.core.series.Series'>

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
data.index#索引

RangeIndex(start=0, stop=4, step=1)

In [6]:
data.values#数据

array([1, 2, 3, 4], dtype=int64)

In [11]:
dict={'CH':'中国','US':'美国','UK':'英国'}
data=pd.Series(dict)
print(type(data))
data

<class 'pandas.core.series.Series'>

CH    中国
US    美国
UK    英国
dtype: object

In [12]:
data.index.name='code'
data.name='country'

In [14]:
data.index

Index(['CH', 'US', 'UK'], dtype='object', name='code')

In [16]:
data.values

array(['中国', '美国', '英国'], dtype=object)

In [21]:
'CH' in data

True

In [17]:
data.iloc[1]

'美国'

In [18]:
data.loc['CH']

'中国'

In [19]:
data[1]

'美国'

In [20]:
data['CH']

'中国'

In [22]:
data.iloc[[0,1,2]]

code
CH    中国
US    美国
UK    英国
Name: country, dtype: object

In [42]:
country1=pd.Series({'name':faker.name(),'job':faker.job(),'ID':faker.ssn()})
country2=pd.Series({'name':faker.name(),'job':faker.job(),'ID':faker.ssn()})
country3=pd.Series({'name':faker.name(),'job':faker.job(),'ID':faker.ssn()})
country4=pd.Series({'name':faker.name(),'job':faker.job(),'ID':faker.ssn()})

In [43]:
df=pd.DataFrame([country1,country2,country3,country4],index=['c1','c2','c3','c4'])

In [44]:
df

   name     job                  ID
c1   袁娟  西班牙语翻译  360502198012272491
c2   李刚    电脑维修  360981197911307232
c3   刘伟    营运主管  620702195704186659
c4   高辉   管道/暖通  330303195307282327

In [48]:
df['age']=[23,25,56,42]

In [49]:
df

   name     job                  ID  age
c1   袁娟  西班牙语翻译  360502198012272491   23
c2   李刚    电脑维修  360981197911307232   25
c3   刘伟    营运主管  620702195704186659   56
c4   高辉   管道/暖通  330303195307282327   42

In [51]:
df['name']

c1    袁娟
c2    李刚
c3    刘伟
c4    高辉
Name: name, dtype: object

In [52]:
df.loc['c2']

name                    李刚
job                   电脑维修
ID      360981197911307232
age                     25
Name: c2, dtype: object

In [53]:
df.iloc[1]

name                    李刚
job                   电脑维修
ID      360981197911307232
age                     25
Name: c2, dtype: object

In [55]:
df['name']['c2']

'李刚'

In [56]:
df['name'].loc['c2']

'李刚'

In [58]:
df['name'].iloc[1]

'李刚'

In [59]:
df.loc['c2']['name']

'李刚'

In [60]:
df.loc['c2'].loc['name']

'李刚'

In [61]:
df.iloc[1]['name']

'李刚'

In [63]:
df.T

,c1,c2,c3,c4
name,袁娟,李刚,刘伟,高辉
job,西班牙语翻译,电脑维修,营运主管,管道/暖通
ID,360502198012272491,360981197911307232,620702195704186659,330303195307282327
age,23,25,56,42

In [64]:
df.drop(['c3'])

   name     job                  ID  age
c1   袁娟  西班牙语翻译  360502198012272491   23
c2   李刚    电脑维修  360981197911307232   25
c4   高辉   管道/暖通  330303195307282327   42

In [66]:
df.drop(['c3'],inplace=True)#对原数据操作

In [67]:
df

   name     job                  ID  age
c1   袁娟  西班牙语翻译  360502198012272491   23
c2   李刚    电脑维修  360981197911307232   25
c4   高辉   管道/暖通  330303195307282327   42

In [68]:
df.drop(['ID'],axis=1)#按列删除

   name     job  age
c1   袁娟  西班牙语翻译   23
c2   李刚    电脑维修   25
c4   高辉   管道/暖通   42

In [69]:
age=df['age']
#age=df['age'].copy()

In [70]:
age+=10

In [71]:
df

   name     job                  ID  age
c1   袁娟  西班牙语翻译  360502198012272491   33
c2   李刚    电脑维修  360981197911307232   35
c4   高辉   管道/暖通  330303195307282327   52

In [75]:
iris=pd.read_csv('iris_data.csv',header=None)
#iris=pd.read_csv('iris_data.csv',header=None,names=['Sepal Length','Sepal Width','Petal Length','Petal Width','type'])
iris

      0    1    2    3                4
0   5.5  2.5  4.0  1.3  Iris-versicolor
1   6.3  2.5  5.0  1.9   Iris-virginica
2   5.5  2.6  4.4  1.2  Iris-versicolor
3   6.0  2.2  4.0  1.0  Iris-versicolor
4   6.0  2.2  5.0  1.5   Iris-virginica
5   6.3  2.8  5.1  1.5   Iris-virginica
6   5.5  2.4  3.8  1.1  Iris-versicolor
7   6.7  3.3  5.7  2.1   Iris-virginica
8   6.7  3.1  4.4  1.4  Iris-versicolor
9   5.6  3.0  4.5  1.5  Iris-versicolor
10  5.7  2.8  4.1  1.3  Iris-versicolor
11  6.3  3.4  5.6  2.4   Iris-virginica
12  5.0  2.0  3.5  1.0  Iris-versicolor
13  6.5  2.8  4.6  1.5  Iris-versicolor
14  5.8  2.7  5.1  1.9   Iris-virginica
15  5.1  2.5  3.0  1.1  Iris-versicolor
16  6.8  3.0  5.5  2.1   Iris-virginica
17  6.3  3.3  4.7  1.6  Iris-versicolor
18  6.4  2.9  4.3  1.3  Iris-versicolor
19  6.6  3.0  4.4  1.4  Iris-versicolor
20  7.6  3.0  6.6  2.1   Iris-virginica
21  5.7  2.9  4.2  1.3  Iris-versicolor
22  5.6  3.0  4.1  1.3  Iris-versicolor
23  5.9  3.2  4.8  1.8  Iris-versicolor
24  6.9  3.1  5.1  2.3   Iris-virginica
25  6.4  3.1  5.5  1.8   Iris-virginica
26  6.5  3.2  5.1  2.0   Iris-virginica
27  7.0  3.2  4.7  1.4  Iris-versicolor
28  6.1  3.0  4.6  1.4  Iris-versicolor
29  7.1  3.0  5.9  2.1   Iris-virginica
..  ...  ...  ...  ...              ...
70  5.7  3.0  4.2  1.2  Iris-versicolor
71  6.1  2.6  5.6  1.4   Iris-virginica
72  7.7  2.8  6.7  2.0   Iris-virginica
73  5.2  2.7  3.9  1.4  Iris-versicolor
74  5.9  3.0  5.1  1.8   Iris-virginica
75  5.6  2.5  3.9  1.1  Iris-versicolor
76  5.7  2.6  3.5  1.0  Iris-versicolor
77  6.3  2.5  4.9  1.5  Iris-versicolor
78  5.6  2.8  4.9  2.0   Iris-virginica
79  5.6  2.7  4.2  1.3  Iris-versicolor
80  6.3  2.3  4.4  1.3  Iris-versicolor
81  6.0  2.7  5.1  1.6  Iris-versicolor
82  6.5  3.0  5.8  2.2   Iris-virginica
83  5.9  3.0  4.2  1.5  Iris-versicolor
84  5.5  2.4  3.7  1.0  Iris-versicolor
85  6.6  2.9  4.6  1.3  Iris-versicolor
86  6.8  3.2  5.9  2.3   Iris-virginica
87  5.8  2.7  5.1  1.9   Iris-virginica
88  6.5  3.0  5.5  1.8   Iris-virginica
89  7.7  2.6  6.9  2.3   Iris-virginica
90  6.7  3.1  5.6  2.4   Iris-virginica
91  6.2  2.2  4.5  1.5  Iris-versicolor
92  5.5  2.3  4.0  1.3  Iris-versicolor
93  6.0  2.9  4.5  1.5  Iris-versicolor
94  7.7  3.8  6.7  2.2   Iris-virginica
95  6.4  3.2  4.5  1.5  Iris-versicolor
96  6.4  2.8  5.6  2.1   Iris-virginica
97  5.7  2.5  5.0  2.0   Iris-virginica
98  6.7  3.0  5.2  2.3   Iris-virginica
99  6.2  2.8  4.8  1.8   Iris-virginica

[100 rows x 5 columns]

In [19]:
iris.head(10)

     0    1    2    3                4
0  5.5  2.5  4.0  1.3  Iris-versicolor
1  6.3  2.5  5.0  1.9   Iris-virginica
2  5.5  2.6  4.4  1.2  Iris-versicolor
3  6.0  2.2  4.0  1.0  Iris-versicolor
4  6.0  2.2  5.0  1.5   Iris-virginica
5  6.3  2.8  5.1  1.5   Iris-virginica
6  5.5  2.4  3.8  1.1  Iris-versicolor
7  6.7  3.3  5.7  2.1   Iris-virginica
8  6.7  3.1  4.4  1.4  Iris-versicolor
9  5.6  3.0  4.5  1.5  Iris-versicolor

In [13]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 5 columns):
5.5                99 non-null float64
2.5                99 non-null float64
4.0                99 non-null float64
1.3                99 non-null float64
Iris-versicolor    99 non-null object
dtypes: float64(4), object(1)
memory usage: 3.9+ KB

In [21]:
iris.describe()

                0           1           2           3
count  100.000000  100.000000  100.000000  100.000000
mean     6.262000    2.872000    4.906000    1.676000
std      0.662834    0.332751    0.825578    0.424769
min      4.900000    2.000000    3.000000    1.000000
25%      5.800000    2.700000    4.375000    1.300000
50%      6.300000    2.900000    4.900000    1.600000
75%      6.700000    3.025000    5.525000    2.000000
max      7.900000    3.800000    6.900000    2.500000

In [40]:
iris.rename(columns={0:'SepalLength',1:'SepalWidth',2:'PetalLength',3:'PetalWidth',4:'type'},inplace=True)

In [37]:
iris.index[0]

0

In [43]:
Iris_virginica=iris[iris['type']=='Iris-virginica']

In [49]:
Iris_virginica[['SepalLength','SepalWidth','PetalLength','PetalWidth']]

    SepalLength  SepalWidth  PetalLength  PetalWidth
1           6.3         2.5          5.0         1.9
4           6.0         2.2          5.0         1.5
5           6.3         2.8          5.1         1.5
7           6.7         3.3          5.7         2.1
11          6.3         3.4          5.6         2.4
14          5.8         2.7          5.1         1.9
16          6.8         3.0          5.5         2.1
20          7.6         3.0          6.6         2.1
24          6.9         3.1          5.1         2.3
25          6.4         3.1          5.5         1.8
26          6.5         3.2          5.1         2.0
29          7.1         3.0          5.9         2.1
30          6.0         3.0          4.8         1.8
33          7.2         3.2          6.0         1.8
35          6.4         2.8          5.6         2.2
37          6.3         3.3          6.0         2.5
38          6.1         3.0          4.9         1.8
39          6.9         3.2          5.7         2.3
40          4.9         2.5          4.5         1.7
41          6.3         2.7          4.9         1.8
42          6.5         3.0          5.2         2.0
48          6.9         3.1          5.4         2.1
49          6.7         3.3          5.7         2.5
51          7.4         2.8          6.1         1.9
52          5.8         2.8          5.1         2.4
53          6.4         2.7          5.3         1.9
54          7.2         3.0          5.8         1.6
55          6.3         2.9          5.6         1.8
56          7.7         3.0          6.1         2.3
57          6.7         2.5          5.8         1.8
58          7.2         3.6          6.1         2.5
59          7.9         3.8          6.4         2.0
61          6.2         3.4          5.4         2.3
67          6.4         3.2          5.3         2.3
69          7.3         2.9          6.3         1.8
71          6.1         2.6          5.6         1.4
72          7.7         2.8          6.7         2.0
74          5.9         3.0          5.1         1.8
78          5.6         2.8          4.9         2.0
82          6.5         3.0          5.8         2.2
86          6.8         3.2          5.9         2.3
87          5.8         2.7          5.1         1.9
88          6.5         3.0          5.5         1.8
89          7.7         2.6          6.9         2.3
90          6.7         3.1          5.6         2.4
94          7.7         3.8          6.7         2.2
96          6.4         2.8          5.6         2.1
97          5.7         2.5          5.0         2.0
98          6.7         3.0          5.2         2.3
99          6.2         2.8          4.8         1.8

In [56]:
iris['country']='CH'

In [61]:
iris_level=iris.set_index(['type','country'])
iris_level

                         SepalLength  SepalWidth  PetalLength  PetalWidth
type            country
Iris-versicolor CH               5.5         2.5          4.0         1.3
Iris-virginica  CH               6.3         2.5          5.0         1.9
Iris-versicolor CH               5.5         2.6          4.4         1.2
                CH               6.0         2.2          4.0         1.0
Iris-virginica  CH               6.0         2.2          5.0         1.5
                CH               6.3         2.8          5.1         1.5
Iris-versicolor CH               5.5         2.4          3.8         1.1
Iris-virginica  CH               6.7         3.3          5.7         2.1
Iris-versicolor CH               6.7         3.1          4.4         1.4
                CH               5.6         3.0          4.5         1.5
                CH               5.7         2.8          4.1         1.3
Iris-virginica  CH               6.3         3.4          5.6         2.4
Iris-versicolor CH               5.0         2.0          3.5         1.0
                CH               6.5         2.8          4.6         1.5
Iris-virginica  CH               5.8         2.7          5.1         1.9
Iris-versicolor CH               5.1         2.5          3.0         1.1
Iris-virginica  CH               6.8         3.0          5.5         2.1
Iris-versicolor CH               6.3         3.3          4.7         1.6
                CH               6.4         2.9          4.3         1.3
                CH               6.6         3.0          4.4         1.4
Iris-virginica  CH               7.6         3.0          6.6         2.1
Iris-versicolor CH               5.7         2.9          4.2         1.3
                CH               5.6         3.0          4.1         1.3
                CH               5.9         3.2          4.8         1.8
Iris-virginica  CH               6.9         3.1          5.1         2.3
                CH               6.4         3.1          5.5         1.8
                CH               6.5         3.2          5.1         2.0
Iris-versicolor CH               7.0         3.2          4.7         1.4
                CH               6.1         3.0          4.6         1.4
Iris-virginica  CH               7.1         3.0          5.9         2.1
...                              ...         ...          ...         ...
Iris-versicolor CH               5.7         3.0          4.2         1.2
Iris-virginica  CH               6.1         2.6          5.6         1.4
                CH               7.7         2.8          6.7         2.0
Iris-versicolor CH               5.2         2.7          3.9         1.4
Iris-virginica  CH               5.9         3.0          5.1         1.8
Iris-versicolor CH               5.6         2.5          3.9         1.1
                CH               5.7         2.6          3.5         1.0
                CH               6.3         2.5          4.9         1.5
Iris-virginica  CH               5.6         2.8          4.9         2.0
Iris-versicolor CH               5.6         2.7          4.2         1.3
                CH               6.3         2.3          4.4         1.3
                CH               6.0         2.7          5.1         1.6
Iris-virginica  CH               6.5         3.0          5.8         2.2
Iris-versicolor CH               5.9         3.0          4.2         1.5
                CH               5.5         2.4          3.7         1.0
                CH               6.6         2.9          4.6         1.3
Iris-virginica  CH               6.8         3.2          5.9         2.3
                CH               5.8         2.7          5.1         1.9
                CH               6.5         3.0          5.5         1.8
                CH               7.7         2.6          6.9         2.3
                CH               6.7         3.1          5.6         2.4
Iris-versicolor CH               6.2         2.2          4.5         1.5
                CH               5.5         2.3          4.0         1.3
                CH               6.0         2.9          4.5         1.5
Iris-virginica  CH               7.7         3.8          6.7         2.2
Iris-versicolor CH               6.4         3.2          4.5         1.5
Iris-virginica  CH               6.4         2.8          5.6         2.1
                CH               5.7         2.5          5.0         2.0
                CH               6.7         3.0          5.2         2.3
                CH               6.2         2.8          4.8         1.8

[100 rows x 4 columns]

In [60]:
iris_level.loc['Iris-virginica','CH']

D:\workspace\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  """Entry point for launching an IPython kernel.

                        SepalLength  SepalWidth  PetalLength  PetalWidth
type           country
Iris-virginica CH               6.3         2.5          5.0         1.9
               CH               6.0         2.2          5.0         1.5
               CH               6.3         2.8          5.1         1.5
               CH               6.7         3.3          5.7         2.1
               CH               6.3         3.4          5.6         2.4
               CH               5.8         2.7          5.1         1.9
               CH               6.8         3.0          5.5         2.1
               CH               7.6         3.0          6.6         2.1
               CH               6.9         3.1          5.1         2.3
               CH               6.4         3.1          5.5         1.8
               CH               6.5         3.2          5.1         2.0
               CH               7.1         3.0          5.9         2.1
               CH               6.0         3.0          4.8         1.8
               CH               7.2         3.2          6.0         1.8
               CH               6.4         2.8          5.6         2.2
               CH               6.3         3.3          6.0         2.5
               CH               6.1         3.0          4.9         1.8
               CH               6.9         3.2          5.7         2.3
               CH               4.9         2.5          4.5         1.7
               CH               6.3         2.7          4.9         1.8
               CH               6.5         3.0          5.2         2.0
               CH               6.9         3.1          5.4         2.1
               CH               6.7         3.3          5.7         2.5
               CH               7.4         2.8          6.1         1.9
               CH               5.8         2.8          5.1         2.4
               CH               6.4         2.7          5.3         1.9
               CH               7.2         3.0          5.8         1.6
               CH               6.3         2.9          5.6         1.8
               CH               7.7         3.0          6.1         2.3
               CH               6.7         2.5          5.8         1.8
               CH               7.2         3.6          6.1         2.5
               CH               7.9         3.8          6.4         2.0
               CH               6.2         3.4          5.4         2.3
               CH               6.4         3.2          5.3         2.3
               CH               7.3         2.9          6.3         1.8
               CH               6.1         2.6          5.6         1.4
               CH               7.7         2.8          6.7         2.0
               CH               5.9         3.0          5.1         1.8
               CH               5.6         2.8          4.9         2.0
               CH               6.5         3.0          5.8         2.2
               CH               6.8         3.2          5.9         2.3
               CH               5.8         2.7          5.1         1.9
               CH               6.5         3.0          5.5         1.8
               CH               7.7         2.6          6.9         2.3
               CH               6.7         3.1          5.6         2.4
               CH               7.7         3.8          6.7         2.2
               CH               6.4         2.8          5.6         2.1
               CH               5.7         2.5          5.0         2.0
               CH               6.7         3.0          5.2         2.3
               CH               6.2         2.8          4.8         1.8

In [71]:
iris_level.sort_index(level=0)

                         SepalLength  SepalWidth  PetalLength  PetalWidth
type            country
Iris-versicolor CH               5.5         2.5          4.0         1.3
                CH               5.5         2.6          4.4         1.2
                CH               6.0         2.2          4.0         1.0
                CH               5.5         2.4          3.8         1.1
                CH               6.7         3.1          4.4         1.4
                CH               5.6         3.0          4.5         1.5
                CH               5.7         2.8          4.1         1.3
                CH               5.0         2.0          3.5         1.0
                CH               6.5         2.8          4.6         1.5
                CH               5.1         2.5          3.0         1.1
                CH               6.3         3.3          4.7         1.6
                CH               6.4         2.9          4.3         1.3
                CH               6.6         3.0          4.4         1.4
                CH               5.7         2.9          4.2         1.3
                CH               5.6         3.0          4.1         1.3
                CH               5.9         3.2          4.8         1.8
                CH               7.0         3.2          4.7         1.4
                CH               6.1         3.0          4.6         1.4
                CH               5.8         2.7          4.1         1.0
                CH               5.8         2.7          3.9         1.2
                CH               6.1         2.9          4.7         1.4
                CH               6.1         2.8          4.7         1.2
                CH               6.1         2.8          4.0         1.3
                CH               6.9         3.1          4.9         1.5
                CH               6.7         3.1          4.7         1.5
                CH               4.9         2.4          3.3         1.0
                CH               5.6         2.9          3.6         1.3
                CH               5.0         2.3          3.3         1.0
                CH               5.8         2.6          4.0         1.2
                CH               6.8         2.8          4.8         1.4
...                              ...         ...          ...         ...
Iris-virginica  CH               6.5         3.0          5.2         2.0
                CH               6.9         3.1          5.4         2.1
                CH               6.7         3.3          5.7         2.5
                CH               7.4         2.8          6.1         1.9
                CH               5.8         2.8          5.1         2.4
                CH               6.4         2.7          5.3         1.9
                CH               7.2         3.0          5.8         1.6
                CH               6.3         2.9          5.6         1.8
                CH               7.7         3.0          6.1         2.3
                CH               6.7         2.5          5.8         1.8
                CH               7.2         3.6          6.1         2.5
                CH               7.9         3.8          6.4         2.0
                CH               6.2         3.4          5.4         2.3
                CH               6.4         3.2          5.3         2.3
                CH               7.3         2.9          6.3         1.8
                CH               6.1         2.6          5.6         1.4
                CH               7.7         2.8          6.7         2.0
                CH               5.9         3.0          5.1         1.8
                CH               5.6         2.8          4.9         2.0
                CH               6.5         3.0          5.8         2.2
                CH               6.8         3.2          5.9         2.3
                CH               5.8         2.7          5.1         1.9
                CH               6.5         3.0          5.5         1.8
                CH               7.7         2.6          6.9         2.3
                CH               6.7         3.1          5.6         2.4
                CH               7.7         3.8          6.7         2.2
                CH               6.4         2.8          5.6         2.1
                CH               5.7         2.5          5.0         2.0
                CH               6.7         3.0          5.2         2.3
                CH               6.2         2.8          4.8         1.8

[100 rows x 4 columns]

In [68]:
set(list(iris['type']))

{'Iris-versicolor', 'Iris-virginica'}

In [78]:
dict={'Iris-versicolor':'1','Iris-virginica':'2'}
iris['class']=iris[4].map(dict)
iris.head()

     0    1    2    3                4 class
0  5.5  2.5  4.0  1.3  Iris-versicolor     1
1  6.3  2.5  5.0  1.9   Iris-virginica     2
2  5.5  2.6  4.4  1.2  Iris-versicolor     1
3  6.0  2.2  4.0  1.0  Iris-versicolor     1
4  6.0  2.2  5.0  1.5   Iris-virginica     2

In [102]:
num=[np.random.randint(20,40) for i in range(10)]
#ages=np.random.randint(20,40,10);
bins=[20,25,30,35,40]

In [107]:
cats=pd.cut(num,bins,labels=['youth','adult','middle','senior'])
cats

[middle, senior, middle, senior, youth, senior, middle, youth, middle, middle]
Categories (4, object): [youth < adult < middle < senior]

In [108]:
cats.categories

Index(['youth', 'adult', 'middle', 'senior'], dtype='object')

In [109]:
cats.codes#分箱编码

array([2, 3, 2, 3, 0, 3, 2, 0, 2, 2], dtype=int8)

In [110]:
pd.value_counts(cats)#统计箱中元素个数

middle    5
senior    3
youth     2
adult     0
dtype: int64

In [111]:
cats.get_values()#获取数据的分箱值

array(['middle', 'senior', 'middle', 'senior', 'youth', 'senior',
       'middle', 'youth', 'middle', 'middle'], dtype=object)

In [115]:
pd.get_dummies(iris[4])

    Iris-versicolor  Iris-virginica
0                 1               0
1                 0               1
2                 1               0
3                 1               0
4                 0               1
5                 0               1
6                 1               0
7                 0               1
8                 1               0
9                 1               0
10                1               0
11                0               1
12                1               0
13                1               0
14                0               1
15                1               0
16                0               1
17                1               0
18                1               0
19                1               0
20                0               1
21                1               0
22                1               0
23                1               0
24                0               1
25                0               1
26                0               1
27                1               0
28                1               0
29                0               1
..              ...             ...
70                1               0
71                0               1
72                0               1
73                1               0
74                0               1
75                1               0
76                1               0
77                1               0
78                0               1
79                1               0
80                1               0
81                1               0
82                0               1
83                1               0
84                1               0
85                1               0
86                0               1
87                0               1
88                0               1
89                0               1
90                0               1
91                1               0
92                1               0
93                1               0
94                0               1
95                1               0
96                0               1
97                0               1
98                0               1
99                0               1

[100 rows x 2 columns]

In [128]:
#数据分组
iris_rename=iris.rename(columns={0:'Sepal Length',1:'Sepal Width',2:'Petal Length',3:'Petal Width',4:'type'})
groups=iris_rename.groupby('type')

type
Iris-versicolor    5.936
Iris-virginica     6.588
Name: Sepal Length, dtype: float64

In [130]:
groups['Sepal Length'].mean()

type
Iris-versicolor    5.936
Iris-virginica     6.588
Name: Sepal Length, dtype: float64

In [132]:
groups.size()

type
Iris-versicolor    50
Iris-virginica     50
dtype: int64

In [135]:
for g,f in groups:
    max=f['Sepal Length'].max()
    min=f['Sepal Length'].min()
    mean=f['Sepal Length'].mean()
    print("{} max:{},min:{},mean:{}".format(g,max,min,mean))

Iris-versicolor max:7.0,min:4.9,mean:5.935999999999998
Iris-virginica max:7.9,min:4.9,mean:6.587999999999998

In [191]:
iris_index=iris.set_index(0)
def get_rank_group(num):
    rank_group=''
    if num<5:
        rank_group=' <5'
    elif num<6:
        rank_group='5~6'
    elif num<7:
        rank_group='6~7'
    else:
        rank_group='>=7'
    return rank_group

groups=iris_index.groupby(get_rank_group)
groups
for g,f in groups:
    print('{}:{}'.format(g,len(f)))

 <5:2
5~6:31
6~7:54
>=7:13